-- Add theoretical-model source tracking fields while preserving existing Source usages.
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'ORG_CHART';
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'JOB_DESCRIPTION';
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'PROCESS_DOCUMENTATION';
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'OTHER';

ALTER TYPE "SourceStatus" ADD VALUE IF NOT EXISTS 'TO_REVIEW';
ALTER TYPE "SourceStatus" ADD VALUE IF NOT EXISTS 'REVIEWED';
ALTER TYPE "SourceStatus" ADD VALUE IF NOT EXISTS 'USED_IN_MODEL';

ALTER TABLE "Source" ADD COLUMN "description" TEXT;
ALTER TABLE "Source" ADD COLUMN "referenceUrl" TEXT;
