-- CreateEnum
CREATE TYPE "NeedStatus" AS ENUM ('DRAFT', 'NEEDS_CLARIFICATION', 'VALIDATED', 'VALIDATED_WITH_OPEN_QUESTIONS');

-- AlterTable
ALTER TABLE "Need" ADD COLUMN "status" "NeedStatus" NOT NULL DEFAULT 'DRAFT';
